babys/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('commodity', include(('commodity.urls', 'commodity'), namespace='commodity')),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('shopper/', include(('shopper.urls', 'shopper'), namespace='shopper')),

    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

commodity/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2022/8/17 19:41
# @Author  : Walter
# @File    : urls.py
# @License : (C)Copyright Walter
# @Desc    :
from django.urls import path
from .views import *

urlpatterns = [
    path('.html', commodityView, name='commodity'),
    path('detail.<int:id>.html', detailView, name='detail'),
]

index/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2022/8/17 19:41
# @Author  : Walter
# @File    : urls.py
# @License : (C)Copyright Walter
# @Desc    :
from django.urls import path
from .views import *

urlpatterns = [
    path('', indexClassView.as_view(), name='index'),
    path('index1', index1, name='index1')
]

shopper/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2022/8/17 19:41
# @Author  : Walter
# @File    : urls.py
# @License : (C)Copyright Walter
# @Desc    :
from django.urls import path
from .views import *

urlpatterns = [
    path('.html', shopperView, name='shopper'),
    path('login.html', loginView, name='login'),
    path('logout.html', logoutView, name='logout'),
    path('shopcart.html', shopcartView, name='shopcart'),
]

commodity/models.py
from django.db import models


# Create your models here.
class Types(models.Model):
    id = models.AutoField(primary_key=True)
    first = models.CharField('一级类型', max_length=100)
    seconds = models.CharField('二级类型', max_length=100)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '商品类型'
        verbose_name_plural = '商品类型'


class CommodityInfos(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField('商品名称', max_length=100)
    size = models.CharField('商品规格', max_length=100)
    types = models.CharField('商品类型', max_length=100)
    price = models.FloatField('商品价格')
    discount = models.FloatField('折后价格')
    stock = models.IntegerField('存货数量')
    sold = models.IntegerField('已售数量')
    like = models.IntegerField('收藏数量')
    created = models.DateField('上架日期', auto_now_add=True)
    img = models.FileField('商品主图', upload_to=r'imgs')
    details = models.FileField('商品介绍', upload_to=r'details')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '商品信息'
        verbose_name_plural = '商品信息'

index/models.py
from django.db import models

# Create your models here.

shopper/models.py
from django.db import models

# Create your models here.
STATE = (
    ('待支付', '待支付'),
    ('已支付', '已支付'),
    ('发货中', '发货中'),
    ('已签收', '已签收'),
    ('退货中', '退货中'),
)


class CarInfos(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField('购买数量')
    commodityInfos_id = models.IntegerField('商品ID')
    user_id = models.IntegerField('用户ID')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = '购物车'

class orderInfos(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.FloatField
    created = models.DateField('创建时间', auto_now_add=True)
    user_id = models.IntegerField('用户ID')
    stage = models.CharField('订单状态', max_length=20, choices=STATE)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = '订单信息'

commodity/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.
def commodityView(request):
    return HttpResponse('commodityView Hello World')


def detailView(request):
    return HttpResponse('Hello World')

    # title = '商品列表'
    # classContent = 'commoditys'

index/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from commodity.models import *

# locals() 函数会以字典类型返回当前位置的全部局部变量
# def indexView(request):
#     title = '首页'
#     classContent = ''
#     commodityInfos = CommodityInfos.objects.order_by('-sold').all()[:8]
#     types = Types.objects.all()
#     c1 = [x.seconds for x in types if x.first == '儿童服饰']
#     clothes = CommodityInfos.objects.filter(types__in=c1).order_by('-sold')[:5]
#     f1 = [x.seconds for x in types if x.first == '奶粉辅食']
#     clothes = CommodityInfos.objects.filter(types__in=f1).order_by('-sold')[:5]
#     g1 = [x.seconds for x in types if x.first == '儿童用品']
#     goods = CommodityInfos.objects.filter(types__in=g1).order_by('-sold')[:5]
#     return render(request, 'index.html', locals())

class indexClassView(TemplateView):
    template_name = 'index.html'
    template_engine = None
    content_type = None
    extra_context = {'title': '首页', 'classContent': ''}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['commodityInfos'] = CommodityInfos.objects.order_by('-sold').all()[:8]
        types = Types.objects.all()
        c1 = [x.seconds for x in types if x.first == '儿童服饰']
        clothes = CommodityInfos.objects.filter(types__in=c1).order_by('-sold')[:5]
        f1 = [x.seconds for x in types if x.first == '奶粉辅食']
        clothes = CommodityInfos.objects.filter(types__in=f1).order_by('-sold')[:5]
        g1 = [x.seconds for x in types if x.first == '儿童用品']
        goods = CommodityInfos.objects.filter(types__in=g1).order_by('-sold')[:5]
        return context


    def get(self, request, *args, **kwargs):
        pass
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


    def post(self, request, *args, **kwargs):
        pass
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)



def index1(request):
    return render(request, 'index1.html', locals())

shopper/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def shopperView(request):
    return HttpResponse('Hello World')


def loginView(request):
    return HttpResponse('Hello World')


def logoutView(request):
    return HttpResponse('Hello World')


def shopcartView(request):
    return HttpResponse('Hello World')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<div class="header">
    <div class="headerLayout w1200">
        <div class="headerCon">

            <h1 class="mallLogo">
                <a href="{% url 'index:index' %}" title="母婴商城">
                    <img src="{% static 'img/logo.png' %}">
                </a>
            </h1>

            <div class="mallSearch">
{#                <form action="{% url commodity:commodity %}" method="get" class="layui-form" novalidate>#}
                <form action="" method="get" class="layui-form" novalidate>
                  <form action="" method="get" class="layui-form" novalidate>
                    <input type="text" name="n" required lay-verify="required" autocomplete="off" class="layui-input"
                           placeholder="请输入需要的商品">
                    <button class="layui-btn" lay-submit lay-filter="formDemo">
                        <i class="layui-icon layui-icon-search"></i>
                    </button>
                    </form>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="content content-nav-base {{ classContent }}">
    <div class="main-nav">
        <div class="inner-cont0">
            <div class="inner-cont1 w1200">
                <div class="inner-cont2">
                    <a href="{% url 'index:index' %}"
                            {% if classContent == '' %} class="active"{% endif %}>
                        首页
                    </a>
                    <a href="{% url 'commodity:commodity' %}"
                            {% if classContent == 'commoditys' %} class="active"{% endif %}>
                        所有商品
                    </a>
                    <a href="{% url 'shopper:shopcart' %}"
                            {% if classContent == 'shopcarts' %} class="active"{% endif %}>
                        购物车
                    </a>
                    <a href="{% url 'shopper:shopper' %}"
                            {% if classContent == 'infomations' %} class="active"{% endif %}>
                        个人中心
                    </a>
                </div>
            </div>
        </div>
    </div>
{% block content %}{% endblock %}
</div>
{% block footer %}
    <script type="text/javascript"></script>
    {% block script %}{% endblock %}
{% endblock footer %}
</body>
</html>

templates/demo.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>示例演示</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 注意：项目正式环境请勿引用该地址 -->
  <link href="//unpkg.com/layui@2.7.6/dist/css/layui.css" rel="stylesheet">
</head>
<body>

<form class="layui-form" action="">
  <div class="layui-form-item">
    <label class="layui-form-label">单行输入框</label>
    <div class="layui-input-block">
      <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="请输入标题" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">验证必填项</label>
    <div class="layui-input-block">
      <input type="text" name="username" lay-verify="required" lay-reqtext="用户名是必填项，岂能为空？" placeholder="请输入" autocomplete="off" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">验证手机</label>
      <div class="layui-input-inline">
        <input type="tel" name="phone" lay-verify="required|phone" autocomplete="off" class="layui-input demo-phone">
      </div>
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">验证码</label>
    <div class="layui-input-inline">
      <input type="text" name="vercode" lay-verify="required" autocomplete="off" class="layui-input">
    </div>
    <div class="layui-form-mid" style="padding: 0!important;">
      <button type="button" class="layui-btn layui-btn-primary" lay-on="get-vercode">获取验证码</button>
    </div>
  </div>
  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">验证邮箱</label>
      <div class="layui-input-inline">
        <input type="text" name="email" lay-verify="email" autocomplete="off" class="layui-input">
      </div>
    </div>
    <div class="layui-inline">
      <label class="layui-form-label">验证日期</label>
      <div class="layui-input-inline">
        <input type="text" name="date" id="date" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
      </div>
    </div>
  </div>
    </form>
</body>
<script>
layui.use(['form', 'util', 'laydate'], function(){
  var form = layui.form;
  var layer = layui.layer;
  var util = layui.util;
  var laydate = layui.laydate;

  //日期
  laydate.render({
    elem: '#date'
  });
  laydate.render({
    elem: '#date1'
  });

  //自定义验证规则
  form.verify({
    title: function(value){
      if(value.length < 5){
        return '标题至少得5个字符啊';
      }
    }
    ,pass: [
      /^[\S]{6,12}$/
      ,'密码必须6到12位，且不能出现空格'
    ]
  });

  //指定开关事件
  form.on('switch(switchTest)', function(data){
    layer.msg('开关checked：'+ (this.checked ? 'true' : 'false'), {
      offset: '6px'
    });
    layer.tips('温馨提示：请注意开关状态的文字可以随意定义，而不仅仅是ON|OFF', data.othis)
  });

  //提交事件
  form.on('submit(demo1)', function(data){
    alert(JSON.stringify(data.field), {
      title: '最终的提交信息'
    })
    return false;
  });

  //表单赋值
  layui.$('#LAY-component-form-setval').on('click', function(){
    form.val('example', {
      "username": "贤心" // "name": "value"
      ,"password": "123456"
      ,"interest": 1
      ,"like[write]": true //复选框选中状态
      ,"close": true //开关状态
      ,"sex": "女"
      ,"desc": "我爱 layui"
    });
  });

  //表单取值
  layui.$('#LAY-component-form-getval').on('click', function(){
    var data = form.val('example');
    alert(JSON.stringify(data));
  });
  // 普通事件
  util.on('lay-on', {
    // 获取验证码
    "get-vercode": function(othis){
      var isvalid = form.validate('.demo-phone'); // v2.7.0 新增
      // 验证通过
      if(isvalid){
        layer.msg('手机号验证通过，执行发送验证码的操作');
      }
    }
  });

});
</script>

</html>

templates/index.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="category-con">
    <div class="category-banner">
        <div class="w1200">
            <img src="{% static 'img/banner1.png' %}">
        </div>
    </div>
</div>
{% endblock %}

templates/index1.html
{% load mytags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% reversal 'Django' %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>